### ISSUE TITLE
Use with new versions of mongodb package fails to connect because of a change in the core mongo driver

### ISSUE THREAD

**Issue by dyladan** [howdyai/botkit-storage-mongo#20]
Monk, which is used by botkit-storage-mongo was using the option `safe` prior to version `4.0.0`.  Versions of mongodb package after 2.2.21 fail to connect giving the following error message:

```
debug:mongodb Cannot connect to mongo +6m
debug:mongodb MongoError: option safe is not supported
```

Option `safe` was removed in monk version 4.0.0 but botkit-storage-mongo is still relying on an old version. Please update to monk 4.0.0 in order to support recent versions of the mongodb driver.

**Comment by benbrown** [comment]
This has been updated! Sorry for the long delay! @dyladan
