### ISSUE TITLE
Add Remove 

### ISSUE THREAD

**Issue by zealot2323** [howdyai/botkit-storage-mongo#30]
Right now there is no way to remove records using this library. This would be helpful and is something the simple storage can already do.

**Comment by alexsmanning** [comment]
@zealot2323:  I just put in a PR for this, it should hopefully get pushed in soon enough!
https://github.com/howdyai/botkit-storage-mongo/pull/31

**Comment by ken9ross** [comment]
@peterswimm Any idea when the PR from alexsmanning is likely to be applied?  I have need of that functionality and would prefer to keep with an unmodified library if possible.

**Comment by peterswimm** [comment]
@ken9ross No timeframe atm, but I will ping the team to take a look.

**Comment by ken9ross** [comment]
Hi @peterswimm Any response to your ping?

**Comment by peterswimm** [comment]
@ken9ross its been merged! Closing this topic for now.

**Comment by ken9ross** [comment]
@peterswimm Any idea as to when npm will receive the updated version?

**Comment by peterswimm** [comment]
@ken9ross I added it to our next sprint, so within the next week or so.

**Comment by ken9ross** [comment]
@peterswimm npm still only reports botkit-storage-mongo as v1.0.6 (ie without delete). Any update on when we can expect it?

**Comment by ken9ross** [comment]
Any update @benbrown (just in case the closed status is throwing you)?

**Comment by Laptopmini** [comment]
Node currently has v1.0.7 which does NOT have the delete method.
I'm gonna pull directly from this git in the mean time.

`npm install howdyai/botkit-storage-mongo --save`

**Comment by nerboda** [comment]
@benbrown any reason this hasn't been pushed to the registry yet?
